apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/sleepr-490610/reservations/production
          name: reservations
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: RESERVATIONS_PORT
              value: '3005'
            - name: RESERVATIONS_HOST
              value: '0.0.0.0'
            - name: AUTH_HOST
              value: 'auth-tcp'
            - name: AUTH_PORT
              value: '3003'
            - name: PAYMENTS_HOST
              value: 'payments'
            - name: PAYMENTS_PORT
              value: '3001'
          ports:
            - containerPort: 3004
            - containerPort: 3005
